# .github/workflows/ai-driven-review.yml
name: AI-Driven Code Review

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      azure_openai_api_key:
        description: 'API Key for Azure OpenAI'
        required: true
        type: string
      language:
        description: 'Programming Langugage'
        required: true
        type: string
    secrets:
      azure_openai_api_key: {}
      language: {}


permissions:
  contents: read
  pull-requests: write   # Allows writing comments to the pull request

jobs:
  code_review:
    runs-on: ubuntu-latest
    env:
      AZURE_OPENAI_API_KEY: ${{ inputs.azure_openai_api_key }}
      LANGUAGE: ${{ inputs.language }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Checkout action repository
        uses: actions/checkout@v4.1.1
        with:
          repository: DXFactor-Solutions/code-guardian
          path: common-repo

      - name: Install yq (YAML Processor) and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Install GitHub CLI (gh)
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Parse the config file and store it as base64 in the environment variable 'content'
      - name: Parse Config File
        id: config
        run: |
          if [ -f common-repo/config/config.yaml ]; then
            echo "content=$(cat common-repo/config/config.yaml | base64 -w 0)" >> $GITHUB_ENV
          else
            echo "Error: config.yaml not found."
            exit 1
          fi

      # Decode the config file from the 'content' environment variable
      - name: Decode Config
        run: |
          if [ -n "${{ env.content }}" ]; then
            echo "${{ env.content }}" | base64 --decode > decoded_config.yaml
            echo "Config file successfully decoded."
          else
            echo "Error: Config content not found."
            exit 1
          fi

      - name: Detect Programming Language
        id: detect_lang
        run: |
          if [ -n "$LANGUAGE" ]; then
            # List of supported languages
            SUPPORTED_LANGUAGES=("nodejs" "python" "ruby")
            if [[ " ${SUPPORTED_LANGUAGES[@]} " =~ " ${LANGUAGE} " ]]; then
              echo "lang=$LANGUAGE" >> $GITHUB_ENV
            else
              echo "lang=unknown" >> $GITHUB_ENV
            fi
          else
            if [ -f package.json ]; then
              echo "lang=nodejs" >> $GITHUB_ENV
            else
              echo "lang=unknown" >> $GITHUB_ENV
            fi
          fi

      - name: Fail if Language Not Supported
        if: env.lang == 'unknown'
        run: |
          echo "Unsupported language detected. Skipping code review."
          exit 1

      - name: Get Language-Specific Prompt
        run: |
          echo "Decoded config contents:"
          cat decoded_config.yaml

          LANG=${{ env.lang }}

          echo "Using language: $LANG"
          SYSTEM_PROMPT_FILE=$(yq e ".languages.${LANG}.system_prompt_file" decoded_config.yaml)
          USER_PROMPT_FILE=$(yq e ".languages.${LANG}.user_prompt_file" decoded_config.yaml)

          echo "System prompt file path: $SYSTEM_PROMPT_FILE"
          echo "User prompt file path: $USER_PROMPT_FILE"

          if [ -f "common-repo/$SYSTEM_PROMPT_FILE" ]; then
            cat "common-repo/$SYSTEM_PROMPT_FILE" > system_prompt.txt
          else
            echo "System prompt file not found: $SYSTEM_PROMPT_FILE"
            exit 1
          fi

          if [ -f "common-repo/$USER_PROMPT_FILE" ]; then
            cat "common-repo/$USER_PROMPT_FILE" > user_prompt.txt
          else
            echo "User prompt file not found: $USER_PROMPT_FILE"
            exit 1
          fi

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Get PR Diff
        uses: GrantBirki/git-diff-action@v2.4.0
        id: git-diff
        with:
          base_branch: origin/${{ github.event.pull_request.base.ref }}  # Use the remote branch reference
          raw_diff_file_output: diff.txt
          file_output_only: "true"
          search_path: "."
          max_buffer_size: 10000000

      - name: Send Azure OpenAI API Request for Code Review
        id: ai_review
        env:
          AZURE_OPENAI_API_KEY: ${{ inputs.azure_openai_api_key }}
        run: |
          DIFF=$(cat ${{ steps.git-diff.outputs.raw-diff-path }})
          SYSTEM_PROMPT=$(cat system_prompt.txt)
          USER_PROMPT=$(cat user_prompt.txt)
          FULL_PROMPT="${USER_PROMPT}\n\nDIFF:\n${DIFF}"

          echo "Request data =>"
          echo "DIFF => $DIFF"
          echo "SYSTEM_PROMPT => $SYSTEM_PROMPT"
          echo "USER_PROMPT => $USER_PROMPT"
          echo "FULL_PROMPT => $FULL_PROMPT"
          echo "AZURE_OPENAI_API_KEY => $AZURE_OPENAI_API_KEY"

          RESPONSE=$(curl -s -X POST https://code-guardians.openai.azure.com/openai/deployments/code-guardians-gpt-4o/chat/completions?api-version=2024-06-01 \
            -H "Content-Type: application/json" \
            -H "api-key: $AZURE_OPENAI_API_KEY" \
            -d '{
              "messages": [{"role": "system", "content": "'"$SYSTEM_PROMPT"'"}, {"role": "user", "content": "'"$FULL_PROMPT"'"}]
            }')

          echo "Response from GPT => $RESPONSE"

          if [[ -z "$RESPONSE" || "$RESPONSE" == "null" ]]; then
            echo "Azure OpenAI response was empty. Exiting..."
            exit 1
          fi

          echo "response=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')" >> $GITHUB_ENV

      - name: Add AI Comments to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE="${{ env.response }}"
          gh pr comment ${{ github.event.pull_request.number }} --body "$RESPONSE"
